DROP TABLE IF EXISTS submissions;
DROP TABLE IF EXISTS assignments;

-- -----------------------------------------------------
-- Table: assignments
-- -----------------------------------------------------
CREATE TABLE assignments (
    assignment_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id          BIGINT NOT NULL,
    title              VARCHAR(255) NOT NULL,
    description        CLOB,
    instructions       CLOB,
    due_date           TIMESTAMP,
    created_by         BIGINT,
    created_at         TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP NOT NULL
);

-- -----------------------------------------------------
-- Table: submissions
-- -----------------------------------------------------
CREATE TABLE submissions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id     BIGINT NOT NULL,
    course_id         BIGINT NOT NULL,
    student_id        BIGINT NOT NULL,
    file_url          CLOB,
    submission_notes  CLOB,
    grade             VARCHAR(50),
    submission_date   TIMESTAMP,
    status            VARCHAR(50),

    CONSTRAINT fk_submission_assignment
        FOREIGN KEY (assignment_id)
        REFERENCES assignments(assignment_id)
        ON DELETE CASCADE
);
